# Generated by Django 5.0.4 on 2026-04-13 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('critical_anomaly', 'Критическая аномалия'), ('device_offline', 'Устройство оффлайн'), ('device_recovered', 'Устройство восстановило связь'), ('disk_critical', 'Критическое заполнение диска'), ('high_temperature', 'Высокая температура CPU'), ('memory_critical', 'Критическое заполнение памяти'), ('repeated_anomaly', 'Повторяющиеся аномалии'), ('incident_created', 'Создан инцидент'), ('incident_escalated', 'Инцидент эскалирован'), ('remote_access_started', 'Начат удалённый доступ'), ('system', 'Системное')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('critical', 'Критично')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'db_table': 'alerts_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'alerts_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
