# Generated by Django 5.0.4 on 2026-04-13 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Обязательная причина подключения (аудит)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Одобрено'), ('active', 'Активно'), ('completed', 'Завершено'), ('expired', 'Истекло'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запрос удалённого доступа',
                'verbose_name_plural': 'Запросы удалённого доступа',
                'db_table': 'remote_access_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteAccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(editable=False, max_length=128, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Одобрено'), ('active', 'Активно'), ('completed', 'Завершено'), ('expired', 'Истекло'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], db_index=True, default='approved', max_length=20)),
                ('tunnel_host', models.CharField(blank=True, max_length=255)),
                ('tunnel_port', models.IntegerField(blank=True, null=True)),
                ('tunnel_type', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('operator_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_reported_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сессия удалённого доступа',
                'verbose_name_plural': 'Сессии удалённого доступа',
                'db_table': 'remote_access_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
