# Generated by Django 5.0.4 on 2026-04-13 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        ('incidents', '0002_initial'),
        ('remote_access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteaccessrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_remote_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remoteaccessrequest',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_access_requests', to='devices.device'),
        ),
        migrations.AddField(
            model_name='remoteaccessrequest',
            name='incident',
            field=models.ForeignKey(blank=True, help_text='Связанный инцидент (если есть)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_access_requests', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='remoteaccessrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remoteaccesssession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='remoteaccesssession',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remoteaccesssession',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='remote_access.remoteaccessrequest'),
        ),
        migrations.AddIndex(
            model_name='remoteaccessrequest',
            index=models.Index(fields=['device', 'created_at'], name='remote_acce_device__593897_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteaccessrequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='remote_acce_request_e21d82_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteaccessrequest',
            index=models.Index(fields=['status'], name='remote_acce_status_0e357a_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteaccesssession',
            index=models.Index(fields=['device', 'created_at'], name='remote_acce_device__50ffc1_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteaccesssession',
            index=models.Index(fields=['operator', 'created_at'], name='remote_acce_operato_351790_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteaccesssession',
            index=models.Index(fields=['status'], name='remote_acce_status_7d2087_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteaccesssession',
            index=models.Index(fields=['token_expires_at'], name='remote_acce_token_e_9af509_idx'),
        ),
    ]
