# Generated by Django 5.0.4 on 2026-04-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_access', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteaccessrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='remoteaccessrequest',
            name='device',
        ),
        migrations.RemoveField(
            model_name='remoteaccessrequest',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='remoteaccessrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='remoteaccesssession',
            name='request',
        ),
        migrations.RemoveIndex(
            model_name='remoteaccesssession',
            name='remote_acce_token_e_9af509_idx',
        ),
        migrations.RemoveField(
            model_name='remoteaccesssession',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='remoteaccesssession',
            name='token_expires_at',
        ),
        migrations.RemoveField(
            model_name='remoteaccesssession',
            name='tunnel_type',
        ),
        migrations.AlterField(
            model_name='remoteaccesssession',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('expired', 'Истекло')], db_index=True, default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='RemoteAccessRequest',
        ),
    ]
