# Generated by Django 5.0.4 on 2026-04-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_access', '0004_add_device_command'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicecommand',
            new_name='remote_acce_device__cb8142_idx',
            old_name='ra_cmd_device_status_idx',
        ),
        migrations.RenameIndex(
            model_name='devicecommand',
            new_name='remote_acce_device__0e943f_idx',
            old_name='ra_cmd_device_created_idx',
        ),
    ]
