# Generated by Django 5.0.4 on 2026-04-13 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('auth_key', models.CharField(editable=False, max_length=128, unique=True)),
                ('auth_key_created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('normal', 'Норма'), ('needs_inspection', 'Требует проверки'), ('needs_reconfiguration', 'Требует перенастройки'), ('site_visit_required', 'Требуется выезд'), ('in_progress', 'В работе'), ('resolved', 'Устранено'), ('false_positive', 'Ложное срабатывание'), ('offline', 'Отключено / нет связи')], db_index=True, default='normal', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_packet_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'db_table': 'devices_device',
            },
        ),
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_temp', models.FloatField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_total_mb', models.IntegerField(blank=True, null=True)),
                ('memory_used_mb', models.IntegerField(blank=True, null=True)),
                ('disk_total_gb', models.FloatField(blank=True, null=True)),
                ('disk_used_gb', models.FloatField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('network_ssid', models.CharField(blank=True, max_length=100)),
                ('signal_strength_dbm', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Heartbeat',
                'verbose_name_plural': 'Heartbeats',
                'db_table': 'devices_heartbeat',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('normal', 'Норма'), ('needs_inspection', 'Требует проверки'), ('needs_reconfiguration', 'Требует перенастройки'), ('site_visit_required', 'Требуется выезд'), ('in_progress', 'В работе'), ('resolved', 'Устранено'), ('false_positive', 'Ложное срабатывание'), ('offline', 'Отключено / нет связи')], max_length=30)),
                ('new_status', models.CharField(choices=[('normal', 'Норма'), ('needs_inspection', 'Требует проверки'), ('needs_reconfiguration', 'Требует перенастройки'), ('site_visit_required', 'Требуется выезд'), ('in_progress', 'В работе'), ('resolved', 'Устранено'), ('false_positive', 'Ложное срабатывание'), ('offline', 'Отключено / нет связи')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('is_automated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'История статусов устройства',
                'verbose_name_plural': 'История статусов устройств',
                'db_table': 'devices_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Месторождение',
                'verbose_name_plural': 'Месторождения',
                'db_table': 'devices_field',
            },
        ),
        migrations.CreateModel(
            name='OperatorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комментарий оператора',
                'verbose_name_plural': 'Комментарии операторов',
                'db_table': 'devices_operator_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PumpJack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Нефтяная качалка',
                'verbose_name_plural': 'Нефтяные качалки',
                'db_table': 'devices_pump_jack',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'devices_region',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Куст скважин',
                'verbose_name_plural': 'Кусты скважин',
                'db_table': 'devices_site',
            },
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware_version', models.CharField(max_length=50)),
                ('model_version', models.CharField(max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('python_version', models.CharField(blank=True, max_length=30)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_info', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Версия ПО',
                'verbose_name_plural': 'Версии ПО',
                'db_table': 'devices_software_version',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
