# Generated by Django 5.0.4 on 2026-04-13 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceheartbeat',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicestatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicestatushistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='devices.device'),
        ),
        migrations.AddField(
            model_name='operatorcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorcomment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='devices.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='pump_jack',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='device', to='devices.pumpjack'),
        ),
        migrations.AddField(
            model_name='field',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='devices.region'),
        ),
        migrations.AddField(
            model_name='site',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='devices.field'),
        ),
        migrations.AddField(
            model_name='pumpjack',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pump_jacks', to='devices.site'),
        ),
        migrations.AddField(
            model_name='softwareversion',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_versions', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='deviceheartbeat',
            index=models.Index(fields=['device', 'received_at'], name='devices_hea_device__11da20_idx'),
        ),
        migrations.AddIndex(
            model_name='devicestatushistory',
            index=models.Index(fields=['device', 'changed_at'], name='devices_sta_device__90a34f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_online'], name='devices_dev_is_onli_19f849_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen_at'], name='devices_dev_last_se_c75af6_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active', 'is_online'], name='devices_dev_is_acti_f4c68a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('region', 'name')},
        ),
        migrations.AddIndex(
            model_name='pumpjack',
            index=models.Index(fields=['latitude', 'longitude'], name='devices_pum_latitud_28c637_idx'),
        ),
        migrations.AddIndex(
            model_name='pumpjack',
            index=models.Index(fields=['site'], name='devices_pum_site_id_fbd726_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pumpjack',
            unique_together={('site', 'well_number')},
        ),
    ]
