# Generated by Django 5.0.4 on 2026-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tunnel_port',
            field=models.IntegerField(blank=True, help_text='Порт обратного SSH-туннеля (20001-20020). Назначается автоматически.', null=True, unique=True),
        ),
    ]
