# Generated by Django 5.0.4 on 2026-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_add_vnc_tunnel_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='tunnel_port',
            field=models.IntegerField(blank=True, help_text='Порт обратного SSH-туннеля (30001-30020). Назначается автоматически.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='vnc_tunnel_port',
            field=models.IntegerField(blank=True, help_text='Порт обратного VNC-туннеля (31001-31020). Назначается автоматически.', null=True, unique=True),
        ),
    ]
