# Generated by Django 5.0.4 on 2026-04-13 02:00

import apps.packets.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClassScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_class', models.CharField(choices=[('normal', 'Норма'), ('noise', 'Шум'), ('grinding', 'Скрежет'), ('squeak', 'Скрип'), ('knock', 'Стук'), ('whistle', 'Свист'), ('foreign_sounds', 'Посторонние звуки'), ('speech', 'Разговоры / речь'), ('other_anomaly', 'Иная аномалия')], db_index=True, max_length=20)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('threshold_exceeded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Оценка класса аудио',
                'verbose_name_plural': 'Оценки классов аудио',
                'db_table': 'packets_class_score',
            },
        ),
        migrations.CreateModel(
            name='DailyDeviceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_packets', models.IntegerField(default=0)),
                ('anomaly_packets', models.IntegerField(default=0)),
                ('critical_packets', models.IntegerField(default=0)),
                ('warning_packets', models.IntegerField(default=0)),
                ('class_counts', models.JSONField(default=dict)),
                ('avg_cpu_temp', models.FloatField(blank=True, null=True)),
                ('avg_cpu_usage', models.FloatField(blank=True, null=True)),
                ('avg_memory_usage_pct', models.FloatField(blank=True, null=True)),
                ('avg_disk_usage_pct', models.FloatField(blank=True, null=True)),
                ('online_minutes', models.IntegerField(default=0)),
                ('heartbeat_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Дневные метрики устройства',
                'verbose_name_plural': 'Дневные метрики устройств',
                'db_table': 'packets_daily_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AudioPacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, max_length=512, null=True, upload_to=apps.packets.models.audio_upload_path)),
                ('audio_file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('audio_sample_rate', models.IntegerField(blank=True, null=True)),
                ('audio_channels', models.SmallIntegerField(blank=True, null=True)),
                ('audio_format', models.CharField(blank=True, max_length=20)),
                ('has_anomaly', models.BooleanField(db_index=True, default=False)),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('critical', 'Критично')], db_index=True, default='info', max_length=10)),
                ('dominant_class', models.CharField(choices=[('normal', 'Норма'), ('noise', 'Шум'), ('grinding', 'Скрежет'), ('squeak', 'Скрип'), ('knock', 'Стук'), ('whistle', 'Свист'), ('foreign_sounds', 'Посторонние звуки'), ('speech', 'Разговоры / речь'), ('other_anomaly', 'Иная аномалия')], db_index=True, default='normal', max_length=20)),
                ('dominant_class_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('status', models.CharField(choices=[('received', 'Получен'), ('processing', 'Обрабатывается'), ('processed', 'Обработан'), ('error', 'Ошибка обработки')], default='received', max_length=15)),
                ('device_cpu_temp', models.FloatField(blank=True, null=True)),
                ('device_cpu_usage', models.FloatField(blank=True, null=True)),
                ('device_memory_usage_pct', models.FloatField(blank=True, null=True)),
                ('device_disk_usage_pct', models.FloatField(blank=True, null=True)),
                ('device_firmware_version', models.CharField(blank=True, max_length=50)),
                ('device_model_version', models.CharField(blank=True, max_length=50)),
                ('raw_analysis', models.JSONField(default=dict)),
                ('operator_status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('reviewed', 'Проверено'), ('false_positive', 'Ложное срабатывание'), ('escalated', 'Передано')], db_index=True, default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('operator_notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_packets', to='devices.device')),
            ],
            options={
                'verbose_name': 'Аудиопакет',
                'verbose_name_plural': 'Аудиопакеты',
                'db_table': 'packets_audio_packet',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
