# Generated by Django 5.0.4 on 2026-04-13 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        ('packets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopacket',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_packets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audioclassscore',
            name='packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_scores', to='packets.audiopacket'),
        ),
        migrations.AddField(
            model_name='dailydevicemetrics',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='audiopacket',
            index=models.Index(fields=['device', 'recorded_at'], name='packets_aud_device__215fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='audiopacket',
            index=models.Index(fields=['device', 'has_anomaly'], name='packets_aud_device__3f5b65_idx'),
        ),
        migrations.AddIndex(
            model_name='audiopacket',
            index=models.Index(fields=['device', 'severity'], name='packets_aud_device__30dc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='audiopacket',
            index=models.Index(fields=['recorded_at', 'has_anomaly'], name='packets_aud_recorde_dd6e61_idx'),
        ),
        migrations.AddIndex(
            model_name='audiopacket',
            index=models.Index(fields=['device', 'operator_status'], name='packets_aud_device__5e5493_idx'),
        ),
        migrations.AddIndex(
            model_name='audioclassscore',
            index=models.Index(fields=['audio_class', 'threshold_exceeded'], name='packets_cla_audio_c_e8dc41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audioclassscore',
            unique_together={('packet', 'audio_class')},
        ),
        migrations.AddIndex(
            model_name='dailydevicemetrics',
            index=models.Index(fields=['date'], name='packets_dai_date_664faf_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydevicemetrics',
            index=models.Index(fields=['device', 'date'], name='packets_dai_device__4c0d48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailydevicemetrics',
            unique_together={('device', 'date')},
        ),
    ]
