# Generated by Django 5.0.4 on 2026-04-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('login_failed', 'Неудачный вход'), ('device_status_changed', 'Смена статуса устройства'), ('incident_created', 'Инцидент создан'), ('incident_status_changed', 'Смена статуса инцидента'), ('packet_reviewed', 'Пакет проверен'), ('remote_access_requested', 'Запрос удалённого доступа'), ('remote_access_approved', 'Удалённый доступ одобрен'), ('remote_access_rejected', 'Удалённый доступ отклонён'), ('remote_session_started', 'Сессия удалённого доступа начата'), ('remote_session_ended', 'Сессия удалённого доступа завершена'), ('device_key_rotated', 'Ключ устройства ротирован'), ('user_created', 'Пользователь создан'), ('user_role_changed', 'Роль пользователя изменена'), ('export', 'Экспорт данных'), ('admin_action', 'Действие администратора')], db_index=True, max_length=50)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('extra_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журнал аудита',
                'db_table': 'common_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
