# Generated by Django 5.0.4 on 2026-04-13 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('audio_anomaly', 'Аудиоаномалия'), ('device_offline', 'Потеря связи'), ('hardware_issue', 'Проблема оборудования'), ('repeated_fault', 'Повторяющийся сбой'), ('disk_full', 'Диск заполнен'), ('high_temperature', 'Высокая температура'), ('manual', 'Создан вручную')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('critical', 'Критично')], db_index=True, default='warning', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('acknowledged', 'Принят'), ('in_progress', 'В работе'), ('resolved', 'Устранён'), ('false_positive', 'Ложное срабатывание'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_class', models.CharField(blank=True, choices=[('', ''), ('normal', 'Норма'), ('noise', 'Шум'), ('grinding', 'Скрежет'), ('squeak', 'Скрип'), ('knock', 'Стук'), ('whistle', 'Свист'), ('foreign_sounds', 'Посторонние звуки'), ('speech', 'Разговоры / речь'), ('other_anomaly', 'Иная аномалия')], max_length=20)),
                ('trigger_score', models.FloatField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_close', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_duplicate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
                'db_table': 'incidents_incident',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комментарий к инциденту',
                'verbose_name_plural': 'Комментарии к инцидентам',
                'db_table': 'incidents_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'Выполняется'), ('done', 'Выполнено'), ('cancelled', 'Отменено')], default='planned', max_length=15)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задача обслуживания',
                'verbose_name_plural': 'Задачи обслуживания',
                'db_table': 'incidents_maintenance_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
