# Generated by Django 5.0.4 on 2026-04-13 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        ('incidents', '0001_initial'),
        ('packets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='devices.device'),
        ),
        migrations.AddField(
            model_name='incident',
            name='parent_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_incidents', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='trigger_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='packets.audiopacket'),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='devices.device'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='incidents.incident'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['device', 'created_at'], name='incidents_i_device__d8f946_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['device', 'status'], name='incidents_i_device__b33438_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', 'status'], name='incidents_i_severit_1a089f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_type', 'status'], name='incidents_i_inciden_b0a029_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['device', 'status'], name='incidents_m_device__bbb99f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['scheduled_date'], name='incidents_m_schedul_9d3cf7_idx'),
        ),
    ]
